# Enable C++ support
language: cpp

sudo: required
dist: trusty

# Compiler selection
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - ninja-build
            - gcc-7
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - cmake
            - cmake-data
            - ninja-build
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

# Install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc++-dev libc++abi-dev libx11-xcb-dev libxrandr-dev libglm-dev libx11-dev
  # Verify cmake versions
  - cmake --version
  # Vulkan SDK
  - wget -O vulkan-sdk.tar.gz https://sdk.lunarg.com/sdk/download/1.1.85.0/linux/vulkansdk-linux-x86_64-1.1.85.0.tar.gz\?Human\=true\;u\=
  - mkdir vulkan-sdk
  - tar zxf vulkan-sdk.tar.gz -C vulkan-sdk --strip-components=1

# Only watch the master branch
branches:
  only:
    - master

# Build steps
script:
  - uname -a
  - $CXX --version
  - export VK_SDK_PATH=$(pwd)/vulkan-sdk/x86_64
  - export VULKAN_SDK=$(pwd)/vulkan-sdk/x86_64
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" ..
  - cmake --build .
