# Enable C++ support
language: cpp

sudo: required
dist: trusty

# Compiler selection
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - ninja-build
            - gcc-7
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" CMAKE_BUILD_TYPE="Debug"
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" CMAKE_BUILD_TYPE="Release"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - cmake
            - cmake-data
            - ninja-build
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" EXTRA_FLAGS="-stdlib=libc++" CMAKE_BUILD_TYPE="Debug"
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" EXTRA_FLAGS="-stdlib=libc++" CMAKE_BUILD_TYPE="Release"

before_install:
  - eval "${MATRIX_EVAL}"

# Install dependencies
install:
  - sudo apt-get update -qq
  # Verify cmake versions
  - cmake --version
  # Vulkan SDK
  - curl https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/linux/vulkan-sdk.tar.gz

# Only watch the master branch
branches:
  only:
    - master

# Build steps
script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" ..
  - cmake --build .
